In [2]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns
import joblib

In [18]:
#load the dataset and inspect shaope and first row
df = pd.read_csv('/Users/ayishahseimela/Desktop/regression_model_comparison/salary.csv', sep=';')
print(df.shape)
df.head()

(3755, 11)

,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
0,2023,SE,FT,Principal Data Scientist,80000,EUR,85847,ES,100,ES,L
1,2023,MI,CT,ML Engineer,30000,USD,30000,US,100,US,S
2,2023,MI,CT,ML Engineer,25500,USD,25500,US,100,US,S
3,2023,SE,FT,Data Scientist,175000,USD,175000,CA,100,CA,M
4,2023,SE,FT,Data Scientist,120000,USD,120000,CA,100,CA,M

In [20]:
#choose the imput features and the salary column as the prediction target
FEATURES = ['job_title', 'experience_level', 'employment_type', 
            'company_location', 'work_year', 'remote_ratio']
TARGET = 'salary_in_usd'

data = df[FEATURES +[TARGET]].copy()
print(data.shape)
data.head()

(3755, 7)

,job_title,experience_level,employment_type,company_location,work_year,remote_ratio,salary_in_usd
0,Principal Data Scientist,SE,FT,ES,2023,100,85847
1,ML Engineer,MI,CT,US,2023,100,30000
2,ML Engineer,MI,CT,US,2023,100,25500
3,Data Scientist,SE,FT,CA,2023,100,175000
4,Data Scientist,SE,FT,CA,2023,100,120000

In [22]:
#removing the duplicates 
before = len(data)
data = data.drop_duplicates()
print(f'Removed {before - len(data)} duplicates. Remaimaining rows: {len(data)}')

Removed 1193 duplicates. Remaimaining rows: 2562

In [29]:
#filter to select job titles and locations
#keep only the most common job titles and group rate locations under others 
ALLOWED_JOBS = ['Data Scientist', 'ML Engineer', 'Data Engineer', 'Data Analyst', 'Research Scientist']
ALLOWED_LOCATIONS = ['US', 'GB', 'CA', 'DE', 'IN', 'FR', 'AU']

#Filters out rows where the job title is NOT in your allowed list
data = data[data['job_title'].isin(ALLOWED_JOBS)]
#Instead of dropping rare locations, it groups them into "Other"
data['company_location'] = data['company_location'].apply(
    lambda x: x if x in ALLOWED_LOCATIONS else 'Other'
)
print(data.shape)
data['job_title'].value_counts()

(1614, 7)

job_title
Data Engineer         594
Data Scientist        528
Data Analyst          393
Research Scientist     65
ML Engineer            34
Name: count, dtype: int64